/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/expert-validation/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifact */
        get: operations["artifact_expert_validation_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expert-validation/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Campaigns */
        get: operations["list_campaigns_expert_validation_campaigns_get"];
        put?: never;
        /** Start Campaign */
        post: operations["start_campaign_expert_validation_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expert-validation/campaigns/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preflight */
        post: operations["preflight_expert_validation_campaigns_preflight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expert-validation/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Campaign */
        get: operations["get_campaign_expert_validation_campaigns__campaign_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expert-validation/campaigns/{campaign_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Campaign */
        post: operations["cancel_campaign_expert_validation_campaigns__campaign_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expert-validation/campaigns/{campaign_id}/full-restart-retries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Campaign */
        post: operations["retry_campaign_expert_validation_campaigns__campaign_id__full_restart_retries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expert-validation/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_expert_validation_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expert-validation/lease": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acquire Lease */
        post: operations["acquire_lease_expert_validation_lease_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expert-validation/lease/{lease_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Renew Lease */
        put: operations["renew_lease_expert_validation_lease__lease_id__put"];
        post?: never;
        /** Release Lease */
        delete: operations["release_lease_expert_validation_lease__lease_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expert-validation/manifests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Manifest */
        post: operations["create_manifest_expert_validation_manifests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expert-validation/manifests/{manifest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Manifest */
        get: operations["get_manifest_expert_validation_manifests__manifest_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disabled Task Runs */
        post: operations["disabled_task_runs_tasks_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactProjectionResponse */
        ArtifactProjectionResponse: {
            /** Artifact Id */
            artifact_id: string;
            /** Attempt Id */
            attempt_id?: string | null;
            /** Batch Id */
            batch_id: string;
            /** Campaign Id */
            campaign_id: string;
            /** Media Type */
            media_type: string;
            /** Pool Generation */
            pool_generation?: number | null;
            /** Role */
            role: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Worker Generation */
            worker_generation?: number | null;
            /** Worker Id */
            worker_id?: string | null;
        };
        /** AttemptProjectionResponse */
        AttemptProjectionResponse: {
            /** Attempt Id */
            attempt_id?: string | null;
            /** Batch Id */
            batch_id?: string | null;
            /** Generation */
            generation: number;
            /**
             * Kind
             * @default FIRST_PASS
             * @enum {string}
             */
            kind: "FIRST_PASS" | "FULL_RESTART_RETRY";
            /** Reason */
            reason?: string | null;
            /** Status */
            status: string;
            /** Worker Generation */
            worker_generation?: number | null;
            /** Worker Id */
            worker_id?: string | null;
        };
        /** BrokerProjectionResponse */
        BrokerProjectionResponse: {
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** CampaignCancelRequest */
        CampaignCancelRequest: {
            /** Command Id */
            command_id: string;
            /** Lease Generation */
            lease_generation: number;
            /** Lease Id */
            lease_id: string;
            /** Service Session Id */
            service_session_id: string;
        };
        /** CampaignConfiguration */
        CampaignConfiguration: {
            /**
             * Execution Mode
             * @enum {string}
             */
            execution_mode: "SEQUENTIAL" | "PARALLEL" | "ADAPTIVE";
            /** Fallback Worker Counts */
            fallback_worker_counts?: number[] | null;
            /** Initial Points Per Worker */
            initial_points_per_worker?: number | null;
            /** Lease Generation */
            lease_generation: number;
            /** Lease Id */
            lease_id: string;
            /** Manifest Id */
            manifest_id: string;
            /** Max Infra Attempts Per Point */
            max_infra_attempts_per_point?: number | null;
            /** Max Points Per Worker */
            max_points_per_worker?: number | null;
            /** Preferred Worker Count */
            preferred_worker_count?: number | null;
            /** Service Session Id */
            service_session_id: string;
            /** Worker Count */
            worker_count?: number | null;
            /** Worker Start Timeout S */
            worker_start_timeout_s?: number | null;
            /** Yolo Executor Count */
            yolo_executor_count?: (1 | 2 | 4) | null;
        };
        /** CampaignProjectionResponse */
        CampaignProjectionResponse: {
            /**
             * Batch Cleanup Complete
             * @default false
             */
            batch_cleanup_complete: boolean;
            /** Batch Id */
            batch_id?: string | null;
            broker?: components["schemas"]["BrokerProjectionResponse"] | null;
            /** Campaign Id */
            campaign_id: string;
            /** Coverage Complete */
            coverage_complete?: boolean | null;
            /** Current Generation */
            current_generation?: number | null;
            /**
             * Evaluated
             * @default 0
             */
            evaluated: number;
            /**
             * Evaluation Coverage
             * @default 0
             */
            evaluation_coverage: number;
            /** Execution Complete */
            execution_complete?: boolean | null;
            /**
             * Execution Coverage
             * @default 0
             */
            execution_coverage: number;
            /** Execution Mode */
            execution_mode?: ("SEQUENTIAL" | "PARALLEL" | "ADAPTIVE") | null;
            /**
             * Execution Started
             * @default 0
             */
            execution_started: number;
            /**
             * Fallback History
             * @default []
             */
            fallback_history: {
                [key: string]: unknown;
            }[];
            /**
             * Indeterminate
             * @default 0
             */
            indeterminate: number;
            /**
             * Infra Attempts
             * @default 0
             */
            infra_attempts: number;
            /**
             * Levels Used
             * @default []
             */
            levels_used: number[];
            /**
             * Not Executed
             * @default 0
             */
            not_executed: number;
            /** Owner Kind */
            owner_kind?: ("COORDINATOR" | "ADAPTIVE_WRAPPER") | null;
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["PointProjectionResponse"][];
            /** Qualification Passed */
            qualification_passed?: boolean | null;
            /** Qualified Success Rate */
            qualified_success_rate?: number | null;
            /**
             * Requested
             * @default 0
             */
            requested: number;
            /**
             * Resource Observations
             * @default {}
             */
            resource_observations: {
                [key: string]: unknown;
            };
            /** Sequence */
            sequence: number;
            /** Status */
            status?: string | null;
            /**
             * Valid Failed
             * @default 0
             */
            valid_failed: number;
            /**
             * Valid Succeeded
             * @default 0
             */
            valid_succeeded: number;
            /**
             * Workers
             * @default []
             */
            workers: components["schemas"]["WorkerProjectionResponse"][];
        };
        /** CampaignStartRequest */
        CampaignStartRequest: {
            /** Command Id */
            command_id: string;
            /**
             * Execution Mode
             * @enum {string}
             */
            execution_mode: "SEQUENTIAL" | "PARALLEL" | "ADAPTIVE";
            /** Fallback Worker Counts */
            fallback_worker_counts?: number[] | null;
            /** Initial Points Per Worker */
            initial_points_per_worker?: number | null;
            /** Lease Generation */
            lease_generation: number;
            /** Lease Id */
            lease_id: string;
            /** Manifest Id */
            manifest_id: string;
            /** Max Infra Attempts Per Point */
            max_infra_attempts_per_point?: number | null;
            /** Max Points Per Worker */
            max_points_per_worker?: number | null;
            /** Preferred Worker Count */
            preferred_worker_count?: number | null;
            /** Preflight Receipt Id */
            preflight_receipt_id: string;
            /** Service Session Id */
            service_session_id: string;
            /** Worker Count */
            worker_count?: number | null;
            /** Worker Start Timeout S */
            worker_start_timeout_s?: number | null;
            /** Yolo Executor Count */
            yolo_executor_count?: (1 | 2 | 4) | null;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /**
             * Adaptive Default Ladder
             * @default [
             *       8,
             *       6,
             *       4,
             *       2,
             *       1
             *     ]
             */
            adaptive_default_ladder: number[];
            /** Available */
            available: boolean;
            /**
             * Default Execution Mode
             * @default SEQUENTIAL
             * @enum {string}
             */
            default_execution_mode: "SEQUENTIAL" | "PARALLEL" | "ADAPTIVE";
            /**
             * Execution Modes
             * @default []
             */
            execution_modes: ("SEQUENTIAL" | "PARALLEL" | "ADAPTIVE")[];
            /**
             * Fixed Max Points Per Worker
             * @default 20
             */
            fixed_max_points_per_worker: number;
            /**
             * Fixed Worker Counts
             * @default [
             *       1,
             *       2,
             *       3
             *     ]
             */
            fixed_worker_counts: number[];
            /**
             * Lease Duration S
             * @default 30
             */
            lease_duration_s: number;
            /**
             * Lease Renewal Margin S
             * @default 10
             */
            lease_renewal_margin_s: number;
            /**
             * Maximum Points
             * @default 20
             */
            maximum_points: number;
            /**
             * Minimum Points
             * @default 4
             */
            minimum_points: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeaseAcquireRequest */
        LeaseAcquireRequest: {
            /** Service Session Id */
            service_session_id: string;
        };
        /** LeaseMutationRequest */
        LeaseMutationRequest: {
            /** Generation */
            generation: number;
            /** Service Session Id */
            service_session_id: string;
        };
        /** LeaseReleaseResponse */
        LeaseReleaseResponse: {
            /** Lease Id */
            lease_id: string;
            /** Released */
            released: boolean;
        };
        /** LeaseResponse */
        LeaseResponse: {
            /** Expires Monotonic Ns */
            expires_monotonic_ns: number;
            /** Generation */
            generation: number;
            /** Lease Id */
            lease_id: string;
            /** Service Session Id */
            service_session_id: string;
        };
        /** ManifestCreateRequest */
        ManifestCreateRequest: {
            /** Total Points */
            total_points: number;
        };
        /** ManifestPointResponse */
        ManifestPointResponse: {
            /** Display Id */
            display_id: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Position World M */
            position_world_m: [
                number,
                number,
                number
            ];
            /**
             * Source
             * @enum {string}
             */
            source: "anchor" | "generated";
            /** Stratum */
            stratum: string;
        };
        /** ManifestResponse */
        ManifestResponse: {
            /** Catalog Sha256 */
            catalog_sha256?: string | null;
            /** Manifest Id */
            manifest_id: string;
            /**
             * Point Count
             * @default 0
             */
            point_count: number;
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["ManifestPointResponse"][];
            /** Selection Sha256 */
            selection_sha256?: string | null;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
        };
        /** PointProjectionResponse */
        PointProjectionResponse: {
            /** Active Worker Id */
            active_worker_id?: string | null;
            /**
             * Artifact Ids
             * @default []
             */
            artifact_ids: string[];
            /**
             * Artifacts
             * @default []
             */
            artifacts: components["schemas"]["ArtifactProjectionResponse"][];
            /**
             * Attempts
             * @default []
             */
            attempts: components["schemas"]["AttemptProjectionResponse"][];
            /** Display Id */
            display_id?: string | null;
            /** Point Id */
            point_id: string;
            /** Reason */
            reason?: string | null;
            /**
             * Retry Eligible
             * @default false
             */
            retry_eligible: boolean;
            /** Status */
            status: string;
        };
        /** PreflightResponse */
        PreflightResponse: {
            /** Admitted */
            admitted: boolean;
            /**
             * Execution Config
             * @default {}
             */
            execution_config: {
                [key: string]: unknown;
            };
            /** Execution Mode */
            execution_mode?: ("SEQUENTIAL" | "PARALLEL" | "ADAPTIVE") | null;
            /** Expires At Monotonic Ns */
            expires_at_monotonic_ns?: number | null;
            /** Manifest Id */
            manifest_id?: string | null;
            /**
             * Reason Codes
             * @default []
             */
            reason_codes: string[];
            /** Receipt Id */
            receipt_id: string;
            /**
             * Resource Observations
             * @default {}
             */
            resource_observations: {
                [key: string]: unknown;
            };
        };
        /** RetryRequest */
        RetryRequest: {
            /** Command Id */
            command_id: string;
            /** Confirmation */
            confirmation: string;
            /** Lease Generation */
            lease_generation: number;
            /** Lease Id */
            lease_id: string;
            /** Point Ids */
            point_ids: string[];
            /** Service Session Id */
            service_session_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkerProjectionResponse */
        WorkerProjectionResponse: {
            /** Current Point Id */
            current_point_id?: string | null;
            /** Generation */
            generation: number;
            /** Heartbeat Deadline Monotonic S */
            heartbeat_deadline_monotonic_s?: number | null;
            /**
             * Lease Count
             * @default 0
             */
            lease_count: number;
            /** Max Points Per Worker */
            max_points_per_worker?: number | null;
            /** Quarantine Reason */
            quarantine_reason?: string | null;
            /** Recovery Result */
            recovery_result?: string | null;
            /** State */
            state: string;
            /** Worker Id */
            worker_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    artifact_expert_validation_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_campaigns_expert_validation_campaigns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignProjectionResponse"][];
                };
            };
        };
    };
    start_campaign_expert_validation_campaigns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignProjectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preflight_expert_validation_campaigns_preflight_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignConfiguration"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreflightResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_campaign_expert_validation_campaigns__campaign_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignProjectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_campaign_expert_validation_campaigns__campaign_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignCancelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignProjectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_campaign_expert_validation_campaigns__campaign_id__full_restart_retries_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignProjectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_expert_validation_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    acquire_lease_expert_validation_lease_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaseAcquireRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renew_lease_expert_validation_lease__lease_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lease_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaseMutationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_lease_expert_validation_lease__lease_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lease_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaseMutationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseReleaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_manifest_expert_validation_manifests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManifestCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManifestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_manifest_expert_validation_manifests__manifest_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manifest_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManifestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    disabled_task_runs_tasks_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
