/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/attachment/{operation}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attachment */
        post: operations["attachment_attachment__operation__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/lease": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acquire Lease */
        post: operations["acquire_lease_control_lease_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/lease/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renew Lease */
        post: operations["renew_lease_control_lease_renew_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/execution/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_execution_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gazebo/camera/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Camera Presets */
        get: operations["camera_presets_gazebo_camera_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gazebo/camera/presets/{preset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Camera Preset */
        post: operations["camera_preset_gazebo_camera_presets__preset__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gazebo/screenshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Screenshot */
        post: operations["screenshot_gazebo_screenshot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gripper/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gripper */
        post: operations["gripper_gripper_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parameters/{operation}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parameters */
        post: operations["parameters_parameters__operation__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/joints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan Joints */
        post: operations["plan_joints_plan_joints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/tcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan Tcp */
        post: operations["plan_tcp_plan_tcp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute */
        post: operations["execute_plans__plan_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/robot/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Home */
        post: operations["home_robot_home_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scene/repair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scene Repair */
        post: operations["scene_repair_scene_repair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Simulation */
        post: operations["reset_simulation_simulation_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Artifact */
        get: operations["task_artifact_tasks_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/captures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Task Capture */
        post: operations["task_capture_tasks_captures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/captures/{capture_id}/rendered-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Task Rendered Image */
        post: operations["task_rendered_image_tasks_captures__capture_id__rendered_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/environment/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Task Shutdown */
        post: operations["task_shutdown_tasks_environment_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Presets */
        get: operations["task_presets_tasks_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/reachability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Task Reachability */
        post: operations["task_reachability_tasks_reachability_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Runs */
        get: operations["task_runs_tasks_runs_get"];
        put?: never;
        /** Task Start */
        post: operations["task_start_tasks_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Status */
        get: operations["task_status_tasks_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Task Cancel */
        post: operations["task_cancel_tasks_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/runs/{run_id}/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Task Recovery */
        post: operations["task_recovery_tasks_runs__run_id__recovery_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow/{operation}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Workflow */
        post: operations["workflow_workflow__operation__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BackendCapabilitiesResponse */
        BackendCapabilitiesResponse: {
            /**
             * Backend
             * @enum {string}
             */
            backend: "gazebo_cpp" | "gazebo_py" | "mujoco_py";
            /** Bind Policy */
            bind_policy: string;
            capabilities: components["schemas"]["BackendCapabilityMap"];
            /** Owner Executable */
            owner_executable: string;
            /** Owner Package */
            owner_package: string;
            /** Simulation Only */
            simulation_only: boolean;
        };
        /** BackendCapabilityMap */
        BackendCapabilityMap: {
            /** Backend Probe */
            backend_probe: boolean;
            /** Camera Presets */
            camera_presets: boolean;
            /** Manual Joint Execute */
            manual_joint_execute: boolean;
            /** Manual Tcp Execute */
            manual_tcp_execute: boolean;
            /** Physical Observation */
            physical_observation: boolean;
            /** Reset World */
            reset_world: boolean;
            /** Scene Operations */
            scene_operations: boolean;
            /** Sensor Capture */
            sensor_capture: boolean;
            /** Task Batch */
            task_batch: boolean;
            /** Task Environment Shutdown */
            task_environment_shutdown: boolean;
            /** Task Reachability */
            task_reachability: boolean;
            /** Workflow Execute */
            workflow_execute: boolean;
            /** Workflow Resume */
            workflow_resume: boolean;
            /** Workflow Run */
            workflow_run: boolean;
            /** Workflow Start */
            workflow_start: boolean;
            /** Workflow Stop */
            workflow_stop: boolean;
        };
        /** CaptureResponse */
        CaptureResponse: {
            /** Artifact Ids */
            artifact_ids?: string[];
            /** Artifacts */
            artifacts?: components["schemas"]["TaskArtifactSummary"][];
            /** Capture Id */
            capture_id: string;
            /** Source Stamp Ns */
            source_stamp_ns?: number | null;
            /** Status */
            status: string;
            /** Summary */
            summary?: {
                [key: string]: unknown;
            };
        };
        /** CollisionPair */
        CollisionPair: {
            /**
             * Allowed
             * @default false
             */
            allowed: boolean;
            /** Depth M */
            depth_m?: number | null;
            /** First Seen At */
            first_seen_at?: number | null;
            /** Last Seen At */
            last_seen_at?: number | null;
            /** Object A */
            object_a: string;
            /** Object B */
            object_b: string;
            /** Source */
            source: string;
            /** Waypoint Index */
            waypoint_index?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JointSample */
        JointSample: {
            /**
             * Age S
             * @default 0
             */
            age_s: number;
            /** Lower Limit Rad */
            lower_limit_rad?: number | null;
            /** Name */
            name: string;
            /** Position Rad */
            position_rad: number;
            /** Upper Limit Rad */
            upper_limit_rad?: number | null;
            /**
             * Velocity Rad S
             * @default 0
             */
            velocity_rad_s: number;
        };
        /** PhysicalOutcomeEvidence */
        PhysicalOutcomeEvidence: {
            /**
             * Duration S
             * @default 0
             */
            duration_s: number;
            final_pose?: components["schemas"]["Pose6D"] | null;
            /** First Sequence */
            first_sequence?: number | null;
            /** Gazebo Attached */
            gazebo_attached?: boolean | null;
            /** Gripper Contact */
            gripper_contact?: boolean | null;
            /** Intended Support Contact */
            intended_support_contact?: boolean | null;
            /** Last Sequence */
            last_sequence?: number | null;
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /** Moveit Attached */
            moveit_attached?: boolean | null;
            /** Primary Failure */
            primary_failure?: string | null;
            /** Release Epoch Id */
            release_epoch_id?: string | null;
            /**
             * Sample Count
             * @default 0
             */
            sample_count: number;
            /** World Object Synchronized */
            world_object_synchronized?: boolean | null;
        };
        /** Pose6D */
        Pose6D: {
            /** Frame Id */
            frame_id: string;
            /** Pitch Rad */
            pitch_rad: number;
            /** Roll Rad */
            roll_rad: number;
            /** Tcp Frame */
            tcp_frame: string;
            /** X M */
            x_m: number;
            /** Y M */
            y_m: number;
            /** Yaw Rad */
            yaw_rad: number;
            /** Z M */
            z_m: number;
        };
        /** ReachabilityResponse */
        ReachabilityResponse: {
            /** Reports */
            reports?: {
                [key: string]: unknown;
            }[];
            /** Simulation Session Id */
            simulation_session_id: string;
            /** Status */
            status: string;
        };
        /** RenderedImageRequest */
        RenderedImageRequest: {
            /** Background Rgb */
            background_rgb: [
                number,
                number,
                number
            ];
            /** Captured At */
            captured_at: string;
            /**
             * Color Mode
             * @enum {string}
             */
            color_mode: "rgb" | "uniform";
            /** Command Id */
            command_id: string;
            /** Displayed Point Count */
            displayed_point_count: number;
            /** Lease Id */
            lease_id: string;
            /** Original Point Count */
            original_point_count: number;
            /** Png Base64 */
            png_base64: string;
            /** Point Size */
            point_size: number;
            /** Projection Matrix */
            projection_matrix: number[];
            /**
             * Sampling Rule
             * @enum {string}
             */
            sampling_rule: "all" | "fixed-stride";
            /** Sampling Stride */
            sampling_stride: number;
            /** Session Id */
            session_id: string;
            /** Source Artifact Id */
            source_artifact_id: string;
            /** Source Sha256 */
            source_sha256: string;
            /** View Matrix */
            view_matrix: number[];
            /** Viewport Px */
            viewport_px: [
                number,
                number
            ];
        };
        /**
         * ServerMode
         * @enum {string}
         */
        ServerMode: "STARTING" | "READ_ONLY" | "READY" | "BUSY" | "DEGRADED";
        /** TaskArtifactSummary */
        TaskArtifactSummary: {
            /** Artifact Id */
            artifact_id: string;
            /** Byte Size */
            byte_size: number;
            /** Media Type */
            media_type: string;
            /** Name */
            name: string;
            /** Sha256 */
            sha256: string;
        };
        /** TaskCaptureRequest */
        TaskCaptureRequest: {
            /** Command Id */
            command_id: string;
            /** Lease Id */
            lease_id: string;
            /** Session Id */
            session_id: string;
        };
        /** TaskMutationRequest */
        TaskMutationRequest: {
            /** Command Id */
            command_id: string;
            /** Lease Id */
            lease_id: string;
            /** Session Id */
            session_id: string;
        };
        /** TaskPointModel */
        TaskPointModel: {
            /** Cup Position World M */
            cup_position_world_m: [
                number,
                number,
                number
            ];
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** TaskPointSummary */
        TaskPointSummary: {
            /** Artifact Ids */
            artifact_ids?: string[];
            /** Failure Code */
            failure_code?: string | null;
            /** Id */
            id: string;
            /** Reachability Status */
            reachability_status?: string | null;
            /** Reset Epoch */
            reset_epoch?: number | null;
            /** Status */
            status: string;
        };
        /** TaskRecoveryRequest */
        TaskRecoveryRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "stop" | "reset-and-continue";
            /** Command Id */
            command_id: string;
            /** Confirmation */
            confirmation: string;
            /** Lease Id */
            lease_id: string;
            /** Session Id */
            session_id: string;
        };
        /** TaskRunRequest */
        TaskRunRequest: {
            /** Command Id */
            command_id: string;
            /** Lease Id */
            lease_id: string;
            /** Points */
            points: components["schemas"]["TaskPointModel"][];
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
            /** Session Id */
            session_id: string;
        };
        /** TaskRunSummary */
        TaskRunSummary: {
            /** First Shared Failure */
            first_shared_failure?: string | null;
            /** Points */
            points?: components["schemas"]["TaskPointSummary"][];
            /** Run Id */
            run_id: string;
            /** Simulation Session Id */
            simulation_session_id: string;
            /** Status */
            status: string;
        };
        /** TaskShutdownRequest */
        TaskShutdownRequest: {
            /** Command Id */
            command_id: string;
            /** Confirmation */
            confirmation: string;
            /** Lease Id */
            lease_id: string;
            /** Session Id */
            session_id: string;
        };
        /** TelemetrySnapshot */
        TelemetrySnapshot: {
            /** Controllers */
            controllers?: {
                [key: string]: string;
            };
            /** Environment */
            environment?: {
                [key: string]: string;
            };
            /** Gazebo Attached */
            gazebo_attached?: boolean | null;
            /** Gazebo Contacts */
            gazebo_contacts?: components["schemas"]["CollisionPair"][];
            /** Joints */
            joints?: {
                [key: string]: components["schemas"]["JointSample"];
            };
            /** @default STARTING */
            mode: components["schemas"]["ServerMode"];
            /** Moveit Attached */
            moveit_attached?: boolean | null;
            /** Moveit Collisions */
            moveit_collisions?: components["schemas"]["CollisionPair"][];
            object_pose?: components["schemas"]["Pose6D"] | null;
            physical_outcome?: components["schemas"]["PhysicalOutcomeEvidence"] | null;
            /** Real Time Factor */
            real_time_factor?: number | null;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /**
             * Scene Revision
             * @default 0
             */
            scene_revision: number;
            /**
             * Sequence
             * @default 0
             */
            sequence: number;
            /**
             * Server Timestamp
             * @default 0
             */
            server_timestamp: number;
            /**
             * Simulation Session Id
             * @default
             */
            simulation_session_id: string;
            /** Source Ages S */
            source_ages_s?: {
                [key: string]: number;
            };
            tcp?: components["schemas"]["Pose6D"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    attachment_attachment__operation__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackendCapabilitiesResponse"];
                };
            };
        };
    };
    acquire_lease_control_lease_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renew_lease_control_lease_renew_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_execution_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    camera_presets_gazebo_camera_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    camera_preset_gazebo_camera_presets__preset__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screenshot_gazebo_screenshot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gripper_gripper_execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    parameters_parameters__operation__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_joints_plan_joints_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_tcp_plan_tcp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_plans__plan_id__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    home_robot_home_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scene_repair_scene_repair_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_simulation_simulation_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetrySnapshot"];
                };
            };
        };
    };
    task_artifact_tasks_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_capture_tasks_captures_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCaptureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_rendered_image_tasks_captures__capture_id__rendered_image_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                capture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderedImageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_shutdown_tasks_environment_shutdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskShutdownRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_presets_tasks_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    task_reachability_tasks_reachability_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReachabilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_runs_tasks_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRunSummary"][];
                };
            };
        };
    };
    task_start_tasks_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_status_tasks_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_cancel_tasks_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskMutationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_recovery_tasks_runs__run_id__recovery_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRecoveryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workflow_workflow__operation__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
