/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/attachment/{operation}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attachment */
        post: operations["attachment_attachment__operation__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/lease": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acquire Lease */
        post: operations["acquire_lease_control_lease_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/lease/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renew Lease */
        post: operations["renew_lease_control_lease_renew_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/execution/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_execution_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gazebo/camera/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Camera Presets */
        get: operations["camera_presets_gazebo_camera_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gazebo/camera/presets/{preset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Camera Preset */
        post: operations["camera_preset_gazebo_camera_presets__preset__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gazebo/screenshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Screenshot */
        post: operations["screenshot_gazebo_screenshot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gripper/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gripper */
        post: operations["gripper_gripper_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parameters/{operation}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parameters */
        post: operations["parameters_parameters__operation__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/joints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan Joints */
        post: operations["plan_joints_plan_joints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/tcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan Tcp */
        post: operations["plan_tcp_plan_tcp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute */
        post: operations["execute_plans__plan_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/robot/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Home */
        post: operations["home_robot_home_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scene/repair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scene Repair */
        post: operations["scene_repair_scene_repair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Simulation */
        post: operations["reset_simulation_simulation_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifact */
        get: operations["artifact_tasks_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/captures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture */
        post: operations["capture_tasks_captures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/captures/{capture_id}/rendered-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rendered Image */
        post: operations["rendered_image_tasks_captures__capture_id__rendered_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/environment/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shutdown */
        post: operations["shutdown_tasks_environment_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Presets */
        get: operations["presets_tasks_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/reachability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reachability */
        post: operations["reachability_tasks_reachability_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_tasks_runs_get"];
        put?: never;
        /** Start */
        post: operations["start_tasks_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_tasks_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_tasks_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/runs/{run_id}/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recovery */
        post: operations["recovery_tasks_runs__run_id__recovery_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow/{operation}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Workflow */
        post: operations["workflow_workflow__operation__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactProjectionResponse */
        ArtifactProjectionResponse: {
            /** Artifact Id */
            artifact_id: string;
            /** Attempt Id */
            attempt_id?: string | null;
            /** Batch Id */
            batch_id: string;
            /** Campaign Id */
            campaign_id: string;
            /** Media Type */
            media_type: string;
            /** Pool Generation */
            pool_generation?: number | null;
            /** Role */
            role: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Worker Generation */
            worker_generation?: number | null;
            /** Worker Id */
            worker_id?: string | null;
        };
        /** AttemptProjectionResponse */
        AttemptProjectionResponse: {
            /** Attempt Id */
            attempt_id?: string | null;
            /** Batch Id */
            batch_id?: string | null;
            /** Generation */
            generation: number;
            /**
             * Kind
             * @default FIRST_PASS
             * @enum {string}
             */
            kind: "FIRST_PASS" | "FULL_RESTART_RETRY";
            /** Reason */
            reason?: string | null;
            /** Status */
            status: string;
            /** Worker Generation */
            worker_generation?: number | null;
            /** Worker Id */
            worker_id?: string | null;
        };
        /** BackendCapabilitiesResponse */
        BackendCapabilitiesResponse: {
            /**
             * Backend
             * @enum {string}
             */
            backend: "gazebo_cpp" | "gazebo_py" | "mujoco_py";
            /** Bind Policy */
            bind_policy: string;
            capabilities: components["schemas"]["BackendCapabilityMap"];
            /** Owner Executable */
            owner_executable: string;
            /** Owner Package */
            owner_package: string;
            /** Simulation Only */
            simulation_only: boolean;
        };
        /** BackendCapabilityMap */
        BackendCapabilityMap: {
            /** Backend Probe */
            backend_probe: boolean;
            /** Camera Presets */
            camera_presets: boolean;
            /** Manual Joint Execute */
            manual_joint_execute: boolean;
            /** Manual Tcp Execute */
            manual_tcp_execute: boolean;
            /** Physical Observation */
            physical_observation: boolean;
            /** Reset World */
            reset_world: boolean;
            /** Scene Operations */
            scene_operations: boolean;
            /** Sensor Capture */
            sensor_capture: boolean;
            /** Task Batch */
            task_batch: boolean;
            /** Task Environment Shutdown */
            task_environment_shutdown: boolean;
            /** Task Reachability */
            task_reachability: boolean;
            /** Workflow Execute */
            workflow_execute: boolean;
            /** Workflow Resume */
            workflow_resume: boolean;
            /** Workflow Run */
            workflow_run: boolean;
            /** Workflow Start */
            workflow_start: boolean;
            /** Workflow Stop */
            workflow_stop: boolean;
        };
        /** BrokerProjectionResponse */
        BrokerProjectionResponse: {
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** CampaignCancelRequest */
        CampaignCancelRequest: {
            /** Command Id */
            command_id: string;
            /** Lease Generation */
            lease_generation: number;
            /** Lease Id */
            lease_id: string;
            /** Service Session Id */
            service_session_id: string;
        };
        /** CampaignConfiguration */
        CampaignConfiguration: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: 3;
            /**
             * Execution Mode
             * @enum {string}
             */
            execution_mode: "SEQUENTIAL" | "PARALLEL" | "ADAPTIVE";
            /** Fallback Worker Counts */
            fallback_worker_counts?: number[] | null;
            /** Initial Points Per Worker */
            initial_points_per_worker?: number | null;
            /** Lease Generation */
            lease_generation: number;
            /** Lease Id */
            lease_id: string;
            /** Manifest Id */
            manifest_id: string;
            /** Max Infra Attempts Per Point */
            max_infra_attempts_per_point?: number | null;
            /** Preferred Worker Count */
            preferred_worker_count?: number | null;
            /** Service Session Id */
            service_session_id: string;
            /** Worker Count */
            worker_count?: number | null;
            /** Worker Start Timeout S */
            worker_start_timeout_s?: number | null;
            /** Yolo Executor Count */
            yolo_executor_count?: (1 | 2 | 4) | null;
        };
        /** CampaignProjectionResponse */
        CampaignProjectionResponse: {
            /**
             * Batch Cleanup Complete
             * @default false
             */
            batch_cleanup_complete: boolean;
            /** Batch Id */
            batch_id?: string | null;
            broker?: components["schemas"]["BrokerProjectionResponse"] | null;
            /** Campaign Id */
            campaign_id: string;
            /** Coverage Complete */
            coverage_complete?: boolean | null;
            /** Current Generation */
            current_generation?: number | null;
            /**
             * Evaluated
             * @default 0
             */
            evaluated: number;
            /**
             * Evaluation Coverage
             * @default 0
             */
            evaluation_coverage: number;
            /** Execution Complete */
            execution_complete?: boolean | null;
            /**
             * Execution Coverage
             * @default 0
             */
            execution_coverage: number;
            /** Execution Mode */
            execution_mode?: ("SEQUENTIAL" | "PARALLEL" | "ADAPTIVE") | null;
            /**
             * Execution Started
             * @default 0
             */
            execution_started: number;
            /**
             * Fallback History
             * @default []
             */
            fallback_history: {
                [key: string]: unknown;
            }[];
            /**
             * Indeterminate
             * @default 0
             */
            indeterminate: number;
            /**
             * Infra Attempts
             * @default 0
             */
            infra_attempts: number;
            /**
             * Levels Used
             * @default []
             */
            levels_used: number[];
            /** Manifest Id */
            manifest_id?: string | null;
            /**
             * Not Executed
             * @default 0
             */
            not_executed: number;
            /** Owner Kind */
            owner_kind?: ("COORDINATOR" | "ADAPTIVE_WRAPPER") | null;
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["PointProjectionResponse"][];
            /** Qualification Passed */
            qualification_passed?: boolean | null;
            /** Qualified Success Rate */
            qualified_success_rate?: number | null;
            /**
             * Requested
             * @default 0
             */
            requested: number;
            /**
             * Resource Observations
             * @default {}
             */
            resource_observations: {
                [key: string]: unknown;
            };
            /** Sequence */
            sequence: number;
            /** Status */
            status?: string | null;
            /**
             * Valid Failed
             * @default 0
             */
            valid_failed: number;
            /**
             * Valid Succeeded
             * @default 0
             */
            valid_succeeded: number;
            /**
             * Workers
             * @default []
             */
            workers: components["schemas"]["WorkerProjectionResponse"][];
        };
        /** CampaignStartRequest */
        CampaignStartRequest: {
            /** Command Id */
            command_id: string;
            /**
             * Contract Version
             * @constant
             */
            contract_version: 3;
            /**
             * Execution Mode
             * @enum {string}
             */
            execution_mode: "SEQUENTIAL" | "PARALLEL" | "ADAPTIVE";
            /** Fallback Worker Counts */
            fallback_worker_counts?: number[] | null;
            /** Initial Points Per Worker */
            initial_points_per_worker?: number | null;
            /** Lease Generation */
            lease_generation: number;
            /** Lease Id */
            lease_id: string;
            /** Manifest Id */
            manifest_id: string;
            /** Max Infra Attempts Per Point */
            max_infra_attempts_per_point?: number | null;
            /** Preferred Worker Count */
            preferred_worker_count?: number | null;
            /** Preflight Receipt Id */
            preflight_receipt_id: string;
            /** Service Session Id */
            service_session_id: string;
            /** Worker Count */
            worker_count?: number | null;
            /** Worker Start Timeout S */
            worker_start_timeout_s?: number | null;
            /** Yolo Executor Count */
            yolo_executor_count?: (1 | 2 | 4) | null;
        };
        /**
         * CapabilitiesResponse
         * @description Capability payload: the original read-only fields plus worker qualification.
         *
         *     The model keeps the reviewed contract name that the generated TypeScript client already
         *     imports, widens ``extra`` to ``allow`` so unknown read-only fields survive, and requires
         *     the per-N qualification list so it is a real, reachable part of the schema.
         */
        CapabilitiesResponse: {
            /**
             * Adaptive Default Ladder
             * @default [
             *       8,
             *       6,
             *       4,
             *       2,
             *       1
             *     ]
             */
            adaptive_default_ladder: number[];
            /** Available */
            available: boolean;
            /**
             * Default Execution Mode
             * @default SEQUENTIAL
             * @enum {string}
             */
            default_execution_mode: "SEQUENTIAL" | "PARALLEL" | "ADAPTIVE";
            /**
             * Execution Modes
             * @default []
             */
            execution_modes: ("SEQUENTIAL" | "PARALLEL" | "ADAPTIVE")[];
            /**
             * Fixed Worker Counts
             * @default [
             *       1,
             *       2,
             *       3,
             *       4,
             *       5,
             *       6,
             *       7,
             *       8
             *     ]
             */
            fixed_worker_counts: number[];
            /**
             * Lease Duration S
             * @default 30
             */
            lease_duration_s: number;
            /**
             * Lease Renewal Margin S
             * @default 10
             */
            lease_renewal_margin_s: number;
            /**
             * Maximum Points
             * @default 20
             */
            maximum_points: number;
            /**
             * Minimum Points
             * @default 4
             */
            minimum_points: number;
            start_guard?: components["schemas"]["StartGuardStatus"] | null;
            start_guard_policy?: components["schemas"]["StartGuardPolicyResponse"] | null;
            /** Worker Count Availability */
            worker_count_availability?: components["schemas"]["WorkerCountAvailability"][];
            /** Worker Qualifications */
            worker_qualifications: components["schemas"]["QualificationViewResponse"][];
        } & {
            [key: string]: unknown;
        };
        /** CaptureResponse */
        CaptureResponse: {
            /** Artifact Ids */
            artifact_ids?: string[];
            /** Artifacts */
            artifacts?: components["schemas"]["TaskArtifactSummary"][];
            /** Capture Id */
            capture_id: string;
            /** Source Stamp Ns */
            source_stamp_ns?: number | null;
            /** Status */
            status: string;
            /** Summary */
            summary?: {
                [key: string]: unknown;
            };
        };
        /** CollisionPair */
        CollisionPair: {
            /**
             * Allowed
             * @default false
             */
            allowed: boolean;
            /** Depth M */
            depth_m?: number | null;
            /** First Seen At */
            first_seen_at?: number | null;
            /** Last Seen At */
            last_seen_at?: number | null;
            /** Object A */
            object_a: string;
            /** Object B */
            object_b: string;
            /** Source */
            source: string;
            /** Waypoint Index */
            waypoint_index?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InstanceProofResponse
         * @description Server-issued document instance. The proof is returned once, to its own document.
         */
        InstanceProofResponse: {
            /** Domain */
            domain: string;
            /** Instance Id */
            instance_id: string;
            /** Proof */
            proof: string;
        };
        /** JointSample */
        JointSample: {
            /**
             * Age S
             * @default 0
             */
            age_s: number;
            /** Lower Limit Rad */
            lower_limit_rad?: number | null;
            /** Name */
            name: string;
            /** Position Rad */
            position_rad: number;
            /** Upper Limit Rad */
            upper_limit_rad?: number | null;
            /**
             * Velocity Rad S
             * @default 0
             */
            velocity_rad_s: number;
        };
        /** LeaseAcquireRequest */
        LeaseAcquireRequest: {
            /** Service Session Id */
            service_session_id: string;
        };
        /** LeaseMutationRequest */
        LeaseMutationRequest: {
            /** Generation */
            generation: number;
            /** Service Session Id */
            service_session_id: string;
        };
        /** LeaseReleaseResponse */
        LeaseReleaseResponse: {
            /** Lease Id */
            lease_id: string;
            /** Released */
            released: boolean;
        };
        /** LeaseResponse */
        LeaseResponse: {
            /** Expires Monotonic Ns */
            expires_monotonic_ns: number;
            /** Generation */
            generation: number;
            /** Lease Id */
            lease_id: string;
            /** Service Session Id */
            service_session_id: string;
        };
        /** ManifestCreateRequest */
        ManifestCreateRequest: {
            /** Total Points */
            total_points: number;
        };
        /** ManifestPointResponse */
        ManifestPointResponse: {
            /** Display Id */
            display_id: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Position World M */
            position_world_m: [
                number,
                number,
                number
            ];
            /**
             * Source
             * @enum {string}
             */
            source: "anchor" | "generated";
            /** Stratum */
            stratum: string;
        };
        /** ManifestResponse */
        ManifestResponse: {
            /** Catalog Seed */
            catalog_seed?: number | null;
            /** Catalog Sha256 */
            catalog_sha256?: string | null;
            /** Geometry Sha256 */
            geometry_sha256?: string | null;
            /** Manifest Id */
            manifest_id: string;
            /** Manifest Sha256 */
            manifest_sha256?: string | null;
            /**
             * Point Count
             * @default 0
             */
            point_count: number;
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["ManifestPointResponse"][];
            /** Sampler Id */
            sampler_id?: string | null;
            /** Sampler Version */
            sampler_version?: number | null;
            /** Selection Sha256 */
            selection_sha256?: string | null;
            /** Source Commit */
            source_commit?: string | null;
            source_hashes?: components["schemas"]["ManifestSourceHashes"] | null;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            top_view?: components["schemas"]["ManifestTopViewResponse"] | null;
        };
        /** ManifestSourceHashes */
        ManifestSourceHashes: {
            /** Adaptive Config */
            adaptive_config: string;
            /** Anchors */
            anchors: string;
            /** Catalog */
            catalog: string;
            /** Dynamic Policy */
            dynamic_policy: string;
            /** Execution Policy */
            execution_policy: string;
            /** Parallel Config */
            parallel_config: string;
            /** Placement Policy */
            placement_policy: string;
            /** Scene */
            scene: string;
            /** Target Mesh */
            target_mesh: string;
            /** Task Scene */
            task_scene: string;
        };
        /** ManifestTopViewResponse */
        ManifestTopViewResponse: {
            /** Cup Footprint Radius Px */
            cup_footprint_radius_px: number;
            geometry: components["schemas"]["MapGeometryResponse"];
            /** Marker Radius Px */
            marker_radius_px: number;
            palette: components["schemas"]["MapPaletteResponse"];
            /** Points */
            points: components["schemas"]["MapPointResponse"][];
            projection: components["schemas"]["MapProjectionResponse"];
            /** Target Tolerance Radius Px */
            target_tolerance_radius_px: number;
        };
        /** MapGeometryResponse */
        MapGeometryResponse: {
            /** Base Bounds */
            base_bounds: [
                number,
                number,
                number,
                number
            ];
            /** Candidate Bounds */
            candidate_bounds: [
                number,
                number,
                number,
                number
            ];
            /** Cup Radius M */
            cup_radius_m: number;
            /** Table Bounds */
            table_bounds: [
                number,
                number,
                number,
                number
            ];
            /** Target Bounds */
            target_bounds: [
                number,
                number,
                number,
                number
            ];
            /** Target Center */
            target_center: [
                number,
                number
            ];
            /** Target Tolerance Radius M */
            target_tolerance_radius_m: number;
        };
        /** MapPaletteResponse */
        MapPaletteResponse: {
            blue: components["schemas"]["MapPaletteStyle"];
            green: components["schemas"]["MapPaletteStyle"];
            red: components["schemas"]["MapPaletteStyle"];
        };
        /** MapPaletteStyle */
        MapPaletteStyle: {
            /** Fill */
            fill: string;
            /**
             * Icon
             * @enum {string}
             */
            icon: "pending" | "passed" | "failed";
            /** Stroke */
            stroke: string;
        };
        /** MapPointResponse */
        MapPointResponse: {
            /** Display Id */
            display_id: string;
            /** Id */
            id: string;
            /** Position World M */
            position_world_m: [
                number,
                number,
                number
            ];
            /** Projected Px */
            projected_px: [
                number,
                number
            ];
        };
        /** MapProjectionResponse */
        MapProjectionResponse: {
            /** Bounds M */
            bounds_m: [
                number,
                number,
                number,
                number
            ];
            /** Height Px */
            height_px: number;
            /** Offset X Px */
            offset_x_px: number;
            /** Offset Y Px */
            offset_y_px: number;
            /** Padding Px */
            padding_px: number;
            /** Pixels Per M */
            pixels_per_m: number;
            /** Width Px */
            width_px: number;
        };
        /** PhysicalOutcomeEvidence */
        PhysicalOutcomeEvidence: {
            /**
             * Duration S
             * @default 0
             */
            duration_s: number;
            final_pose?: components["schemas"]["Pose6D"] | null;
            /** First Sequence */
            first_sequence?: number | null;
            /** Gazebo Attached */
            gazebo_attached?: boolean | null;
            /** Gripper Contact */
            gripper_contact?: boolean | null;
            /** Intended Support Contact */
            intended_support_contact?: boolean | null;
            /** Last Sequence */
            last_sequence?: number | null;
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /** Moveit Attached */
            moveit_attached?: boolean | null;
            /** Primary Failure */
            primary_failure?: string | null;
            /** Release Epoch Id */
            release_epoch_id?: string | null;
            /**
             * Sample Count
             * @default 0
             */
            sample_count: number;
            /** World Object Synchronized */
            world_object_synchronized?: boolean | null;
        };
        /** PointProjectionResponse */
        PointProjectionResponse: {
            /** Active Worker Id */
            active_worker_id?: string | null;
            /**
             * Artifact Ids
             * @default []
             */
            artifact_ids: string[];
            /**
             * Artifacts
             * @default []
             */
            artifacts: components["schemas"]["ArtifactProjectionResponse"][];
            /**
             * Attempts
             * @default []
             */
            attempts: components["schemas"]["AttemptProjectionResponse"][];
            /** Display Id */
            display_id?: string | null;
            /** Point Id */
            point_id: string;
            /** Reason */
            reason?: string | null;
            /**
             * Retry Eligible
             * @default false
             */
            retry_eligible: boolean;
            /** Status */
            status: string;
        };
        /** Pose6D */
        Pose6D: {
            /** Frame Id */
            frame_id: string;
            /** Pitch Rad */
            pitch_rad: number;
            /** Roll Rad */
            roll_rad: number;
            /** Tcp Frame */
            tcp_frame: string;
            /** X M */
            x_m: number;
            /** Y M */
            y_m: number;
            /** Yaw Rad */
            yaw_rad: number;
            /** Z M */
            z_m: number;
        };
        /** PreflightResponse */
        PreflightResponse: {
            /** Admitted */
            admitted: boolean;
            /**
             * Execution Config
             * @default {}
             */
            execution_config: {
                [key: string]: unknown;
            };
            /** Execution Mode */
            execution_mode?: ("SEQUENTIAL" | "PARALLEL" | "ADAPTIVE") | null;
            /** Expires At Monotonic Ns */
            expires_at_monotonic_ns?: number | null;
            /** Manifest Id */
            manifest_id?: string | null;
            /**
             * Reason Codes
             * @default []
             */
            reason_codes: string[];
            /** Receipt Id */
            receipt_id: string;
            /**
             * Resource Observations
             * @default {}
             */
            resource_observations: {
                [key: string]: unknown;
            };
            start_guard?: components["schemas"]["StartGuardStatus"] | null;
        };
        /**
         * QualificationViewResponse
         * @description Pydantic mirror of the budget provider's read-only view; generated into the schema.
         */
        QualificationViewResponse: {
            /** Approval Sha256 */
            approval_sha256: string | null;
            /** Contract Version */
            contract_version: number;
            /** Profile Sha256 */
            profile_sha256: string | null;
            /** Reasons */
            reasons: string[];
            /** Runtime Identity */
            runtime_identity: string;
            /** Selected N */
            selected_n: number;
            /** Status */
            status: string;
        };
        /** ReachabilityResponse */
        ReachabilityResponse: {
            /** Reports */
            reports?: {
                [key: string]: unknown;
            }[];
            /** Simulation Session Id */
            simulation_session_id: string;
            /** Status */
            status: string;
        };
        /** RenderedImageRequest */
        RenderedImageRequest: {
            /** Background Rgb */
            background_rgb: [
                number,
                number,
                number
            ];
            /** Captured At */
            captured_at: string;
            /**
             * Color Mode
             * @enum {string}
             */
            color_mode: "rgb" | "uniform";
            /** Command Id */
            command_id: string;
            /** Displayed Point Count */
            displayed_point_count: number;
            /** Lease Id */
            lease_id: string;
            /** Original Point Count */
            original_point_count: number;
            /** Png Base64 */
            png_base64: string;
            /** Point Size */
            point_size: number;
            /** Projection Matrix */
            projection_matrix: number[];
            /**
             * Sampling Rule
             * @enum {string}
             */
            sampling_rule: "all" | "fixed-stride";
            /** Sampling Stride */
            sampling_stride: number;
            /** Session Id */
            session_id: string;
            /** Source Artifact Id */
            source_artifact_id: string;
            /** Source Sha256 */
            source_sha256: string;
            /** View Matrix */
            view_matrix: number[];
            /** Viewport Px */
            viewport_px: [
                number,
                number
            ];
        };
        /** RetryRequest */
        RetryRequest: {
            /** Command Id */
            command_id: string;
            /** Confirmation */
            confirmation: string;
            /** Lease Generation */
            lease_generation: number;
            /** Lease Id */
            lease_id: string;
            /** Point Ids */
            point_ids: string[];
            /** Service Session Id */
            service_session_id: string;
        };
        /**
         * ServerMode
         * @enum {string}
         */
        ServerMode: "STARTING" | "READ_ONLY" | "READY" | "BUSY" | "DEGRADED";
        /**
         * StartGuardCheck
         * @description One check of the shared startup guard, in the units the decision used.
         */
        StartGuardCheck: {
            /** Cutoff */
            cutoff?: number | null;
            /** Observed */
            observed?: number | string | null;
            /** Reason */
            reason: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PASS" | "WARN" | "FAIL";
            /** Unit */
            unit: string;
        };
        /**
         * StartGuardPolicyResponse
         * @description The enforced policy, so a client can display the cutoffs it was judged against.
         *
         *     ``mps_minimum_headroom_bytes`` is present only for the schema-v4 macOS MPS combination. It is
         *     the fixed unified-memory floor, reported so a client can show the cutoff that refused a start;
         *     it is not a capacity certification and it does not scale with the worker count.
         */
        StartGuardPolicyResponse: {
            /** Cpu Busy Warn Fraction */
            cpu_busy_warn_fraction: number;
            /** Gpu Minimum Bytes */
            gpu_minimum_bytes: number;
            /** Mps Minimum Headroom Bytes */
            mps_minimum_headroom_bytes?: number | null;
            /** Ram Minimum Bytes */
            ram_minimum_bytes: number;
            /** Ram Minimum Fraction */
            ram_minimum_fraction: number;
            /** Timeout S */
            timeout_s: number;
        };
        /**
         * StartGuardStatus
         * @description The server's own decision. A client cannot supply or overwrite it.
         *
         *     ``admission_kind`` labels what the accelerator check actually measured. On the macOS MPS
         *     combination it is ``unified-memory-proxy``: a host unified-memory figure, not a device-level
         *     free-VRAM reading. Leaving it null is honest for a snapshot that carries no accelerator check.
         */
        StartGuardStatus: {
            /** Admission Kind */
            admission_kind?: string | null;
            /**
             * Checks
             * @default {}
             */
            checks: {
                [key: string]: components["schemas"]["StartGuardCheck"];
            };
            /**
             * Cleanup State
             * @default CLEAR
             * @enum {string}
             */
            cleanup_state: "CLEAR" | "PROBE_CLEANUP_BLOCKED";
            /** Gpu Uuid */
            gpu_uuid?: string | null;
            /** Observed Monotonic S */
            observed_monotonic_s?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PASS" | "WARN" | "FAIL";
        };
        /** TaskArtifactSummary */
        TaskArtifactSummary: {
            /** Artifact Id */
            artifact_id: string;
            /** Byte Size */
            byte_size: number;
            /** Media Type */
            media_type: string;
            /** Name */
            name: string;
            /** Sha256 */
            sha256: string;
        };
        /** TaskCaptureRequest */
        TaskCaptureRequest: {
            /** Command Id */
            command_id: string;
            /** Lease Id */
            lease_id: string;
            /** Session Id */
            session_id: string;
        };
        /** TaskMutationRequest */
        TaskMutationRequest: {
            /** Command Id */
            command_id: string;
            /** Lease Id */
            lease_id: string;
            /** Session Id */
            session_id: string;
        };
        /** TaskPointModel */
        TaskPointModel: {
            /** Cup Position World M */
            cup_position_world_m: [
                number,
                number,
                number
            ];
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** TaskPointSummary */
        TaskPointSummary: {
            /** Artifact Ids */
            artifact_ids?: string[];
            /** Artifacts */
            artifacts?: components["schemas"]["TaskArtifactSummary"][];
            /** Failure Code */
            failure_code?: string | null;
            /** Id */
            id: string;
            /** Reachability Status */
            reachability_status?: string | null;
            /** Reset Epoch */
            reset_epoch?: number | null;
            /** Status */
            status: string;
        };
        /** TaskRecoveryRequest */
        TaskRecoveryRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "stop" | "reset-and-continue";
            /** Command Id */
            command_id: string;
            /** Confirmation */
            confirmation: string;
            /** Lease Id */
            lease_id: string;
            /** Session Id */
            session_id: string;
        };
        /** TaskRunRequest */
        TaskRunRequest: {
            /** Command Id */
            command_id: string;
            /** Lease Id */
            lease_id: string;
            /** Points */
            points: components["schemas"]["TaskPointModel"][];
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
            /** Session Id */
            session_id: string;
        };
        /** TaskRunSummary */
        TaskRunSummary: {
            /** First Shared Failure */
            first_shared_failure?: string | null;
            /** Points */
            points?: components["schemas"]["TaskPointSummary"][];
            /** Run Id */
            run_id: string;
            /** Simulation Session Id */
            simulation_session_id: string;
            /** Status */
            status: string;
        };
        /** TaskShutdownRequest */
        TaskShutdownRequest: {
            /** Command Id */
            command_id: string;
            /** Confirmation */
            confirmation: string;
            /** Lease Id */
            lease_id: string;
            /** Session Id */
            session_id: string;
        };
        /** TelemetrySnapshot */
        TelemetrySnapshot: {
            /** Controllers */
            controllers?: {
                [key: string]: string;
            };
            /** Environment */
            environment?: {
                [key: string]: string;
            };
            /** Gazebo Attached */
            gazebo_attached?: boolean | null;
            /** Gazebo Contacts */
            gazebo_contacts?: components["schemas"]["CollisionPair"][];
            /** Joints */
            joints?: {
                [key: string]: components["schemas"]["JointSample"];
            };
            /** @default STARTING */
            mode: components["schemas"]["ServerMode"];
            /** Moveit Attached */
            moveit_attached?: boolean | null;
            /** Moveit Collisions */
            moveit_collisions?: components["schemas"]["CollisionPair"][];
            object_pose?: components["schemas"]["Pose6D"] | null;
            physical_outcome?: components["schemas"]["PhysicalOutcomeEvidence"] | null;
            /** Real Time Factor */
            real_time_factor?: number | null;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /**
             * Scene Revision
             * @default 0
             */
            scene_revision: number;
            /**
             * Sequence
             * @default 0
             */
            sequence: number;
            /**
             * Server Timestamp
             * @default 0
             */
            server_timestamp: number;
            /**
             * Simulation Session Id
             * @default
             */
            simulation_session_id: string;
            /** Source Ages S */
            source_ages_s?: {
                [key: string]: number;
            };
            tcp?: components["schemas"]["Pose6D"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkerCountAvailability */
        WorkerCountAvailability: {
            /** Profile Sha256 */
            profile_sha256?: string | null;
            /** Qualification Sha256 */
            qualification_sha256?: string | null;
            /**
             * Reason Codes
             * @default []
             */
            reason_codes: string[];
            /** Selectable */
            selectable: boolean;
            /** Status */
            status: string;
            /** Worker Count */
            worker_count: number;
        };
        /** WorkerProjectionResponse */
        WorkerProjectionResponse: {
            /** Current Point Id */
            current_point_id?: string | null;
            /** Generation */
            generation: number;
            /** Heartbeat Deadline Monotonic S */
            heartbeat_deadline_monotonic_s?: number | null;
            /**
             * Lease Count
             * @default 0
             */
            lease_count: number;
            /** Max Points Per Worker */
            max_points_per_worker?: number | null;
            /** Quarantine Reason */
            quarantine_reason?: string | null;
            /** Recovery Result */
            recovery_result?: string | null;
            /** State */
            state: string;
            /** Worker Id */
            worker_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    attachment_attachment__operation__post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path: {
                operation: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackendCapabilitiesResponse"];
                };
            };
        };
    };
    acquire_lease_control_lease_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renew_lease_control_lease_renew_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_execution_cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    camera_presets_gazebo_camera_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    camera_preset_gazebo_camera_presets__preset__post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path: {
                preset: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screenshot_gazebo_screenshot_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gripper_gripper_execute_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    parameters_parameters__operation__post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path: {
                operation: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_joints_plan_joints_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_tcp_plan_tcp_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_plans__plan_id__execute_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    home_robot_home_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scene_repair_scene_repair_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_simulation_simulation_reset_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetrySnapshot"];
                };
            };
        };
    };
    artifact_tasks_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_tasks_captures_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCaptureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rendered_image_tasks_captures__capture_id__rendered_image_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path: {
                capture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderedImageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shutdown_tasks_environment_shutdown_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskShutdownRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presets_tasks_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    reachability_tasks_reachability_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReachabilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_tasks_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRunSummary"][];
                };
            };
        };
    };
    start_tasks_runs_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_tasks_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_tasks_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskMutationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recovery_tasks_runs__run_id__recovery_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRecoveryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workflow_workflow__operation__post: {
        parameters: {
            query?: never;
            header?: {
                "X-SO101-Instance-ID"?: string | null;
                "X-SO101-Instance-Proof"?: string | null;
                "X-SO101-Channel-Revision"?: string | null;
                "X-SO101-Execution-Generation"?: string | null;
            };
            path: {
                operation: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
