// Copyright 2026 zjumty
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef SO101_MUJOCO_SUPPORT__BOUND_RESERVATION_HPP_
#define SO101_MUJOCO_SUPPORT__BOUND_RESERVATION_HPP_

#include <array>
#include <cstdint>
#include <string>

#include "so101_mujoco_support/controller_goal_types.hpp"
#include "so101_mujoco_support/controller_reservation_role.hpp"

namespace so101_mujoco_support
{

// Frozen v2 bound reservation schema. The binding block is explicit and separate
// from the goal bytes, so a legacy reserve can never treat a bound frame as a bare
// goal. The gate never trusts a digest carried in this struct: it re-serializes
// `goal` and hashes it outside the lock on every reserve/admit.
constexpr uint8_t kBoundProtocolVersion = 2;
constexpr uint8_t kBoundReservationOperation = 1;
constexpr uint32_t kMaxBoundBodyBytes = 1048640;
constexpr size_t kMaxIncarnationBytes = 64;
constexpr size_t kMaxGoalCdrBytes = 1048576;

// Service-owned controller identity, generated by the C++ service and injected at
// construction. It is bound to one role; there is deliberately no runtime setter.
struct ServiceControllerIdentity
{
  ControllerReservationRole role{ControllerReservationRole::ARM};
  std::string incarnation;
  std::string boot;
};

enum class BoundReserveStatus : uint8_t
{
  ACCEPTED = 0,
  DENY_EXPIRED,
  DENY_DIGEST_MISMATCH,
  DENY_UUID_REPLAY,
  DENY_GENERATION,
  DENY_INCARNATION,
  DENY_BOOT,
  DENY_ROLE,
  DENY_CLOSED,
};

// Service-owned identity generation and its frozen bounded binary reply.
constexpr uint8_t kIdentityProtocolVersion = 1;
constexpr uint8_t kIdentityQueryOperation = 1;
constexpr size_t kMaxIdentityReplyBytes = 160;

ServiceControllerIdentity generate_service_identity(
  ControllerReservationRole role, const std::array<uint8_t, 32> & capability);

std::vector<uint8_t> encode_identity_reply(
  ControllerReservationRole role, uint64_t generation, const std::string & incarnation,
  const std::string & boot);

bool parse_identity_reply(
  const std::vector<uint8_t> & reply,
  ControllerReservationRole expected_role, ServiceControllerIdentity * out);

struct BoundControllerReservationRequest
{
  uint64_t generation{0};
  std::array<uint8_t, 16> permit_uuid{};
  ControllerReservationRole role{ControllerReservationRole::ARM};
  ControllerGoalUUID uuid{};
  std::array<uint8_t, 32> target_digest{};
  int64_t claim_monotonic_ns{0};
  int64_t deadline_ns{0};
  std::string session_id;
  std::string broker_incarnation;
  std::string controller_incarnation;
  std::string controller_boot_incarnation;
  ControllerGoal goal;
};

}  // namespace so101_mujoco_support

#endif  // SO101_MUJOCO_SUPPORT__BOUND_RESERVATION_HPP_
